Repository Gp2mv3/Syntheses, pull requests merged in 2018-08, with the labels that each got.

#566 Rename telecom-1930 to introtelecom-1930
  src/q6/introtelecom-ELEC1930/exercises/Makefile
  src/q6/introtelecom-ELEC1930/exercises/introtelecom-ELEC1930-exercises.tex
  src/q6/introtelecom-ELEC1930/exercises/telecom_tp1.tex
  src/q6/introtelecom-ELEC1930/exercises/telecom_tp2.tex
  src/q6/introtelecom-ELEC1930/exercises/telecom_tp3.tex
  src/q6/introtelecom-ELEC1930/introtelecom-ELEC1930.mk
  src/q6/introtelecom-ELEC1930/summary/Makefile
  src/q6/introtelecom-ELEC1930/summary/demodulateur.tex
  src/q6/introtelecom-ELEC1930/summary/img/algorithme_asymetrique.png
  src/q6/introtelecom-ELEC1930/summary/img/angle.png
  src/q6/introtelecom-ELEC1930/summary/img/anneau.png
  src/q6/introtelecom-ELEC1930/summary/img/autres.png
  src/q6/introtelecom-ELEC1930/summary/img/bande.png
  src/q6/introtelecom-ELEC1930/summary/img/biphase.png
  src/q6/introtelecom-ELEC1930/summary/img/bus.png
  src/q6/introtelecom-ELEC1930/summary/img/demo.png
  src/q6/introtelecom-ELEC1930/summary/img/dipole.png
  src/q6/introtelecom-ELEC1930/summary/img/dispersion.png
  src/q6/introtelecom-ELEC1930/summary/img/endfire.png
  src/q6/introtelecom-ELEC1930/summary/img/etoile.png
  src/q6/introtelecom-ELEC1930/summary/img/exo.png
  src/q6/introtelecom-ELEC1930/summary/img/fdma_tdma_cdma.png
  src/q6/introtelecom-ELEC1930/summary/img/go_back_n.png
  src/q6/introtelecom-ELEC1930/summary/img/indice_de_modulation_AM.png
  src/q6/introtelecom-ELEC1930/summary/img/mapping.png
  src/q6/introtelecom-ELEC1930/summary/img/miller.png
  src/q6/introtelecom-ELEC1930/summary/img/modulation_am_fm.png
  src/q6/introtelecom-ELEC1930/summary/img/par.png
  src/q6/introtelecom-ELEC1930/summary/img/quantification_signal.png
  src/q6/introtelecom-ELEC1930/summary/img/reception_superheterodyne.png
  src/q6/introtelecom-ELEC1930/summary/img/reseau.png
  src/q6/introtelecom-ELEC1930/summary/img/selective_repeat.png
  src/q6/introtelecom-ELEC1930/summary/img/signal_modulant.png
  src/q6/introtelecom-ELEC1930/summary/img/signal_module.png
  src/q6/introtelecom-ELEC1930/summary/img/signal_porteur.png
  src/q6/introtelecom-ELEC1930/summary/img/spatial.png
  src/q6/introtelecom-ELEC1930/summary/img/stereo.png
  src/q6/introtelecom-ELEC1930/summary/img/stop_and_wait.png
  src/q6/introtelecom-ELEC1930/summary/img/structure_reseau_gsm.png
  src/q6/introtelecom-ELEC1930/summary/img/yagi.png
  src/q6/introtelecom-ELEC1930/summary/introtelecom-ELEC1930-summary.tex
  src/q6/telecom-ELEC1930/summary/Makefile
  src/q6/telecom-ELEC1930/summary/telecom_tp1.tex
  src/q6/telecom-ELEC1930/summary/telecom_tp2.tex
  src/q6/telecom-ELEC1930/summary/telecom_tp3.tex
  src/q6/telecom-ELEC1930/telecom-ELEC1930.mk
Labels: Amélioration

#565 Add math 3 exam 2018 août
  src/eplcommon.sty
  src/q3/math-FSAB1103/exam/2018/Août/All/Makefile
  src/q3/math-FSAB1103/exam/2018/Août/All/math-FSAB1103-exam-2018-Août-All.tex
  src/q3/math-FSAB1103/exam/2018/Août/Août.mk
Labels: Ajout

#573 Small correction in math 3 exams.
  src/q3/math-FSAB1103/exam/2016/Août/All/math-FSAB1103-exam-2016-Août-All.tex
  src/q3/math-FSAB1103/exam/2017/Janvier/All/math-FSAB1103-exam-2017-Janvier-All.tex
Labels: Amélioration

#572 Change min to maj
  src/q6/mft-MECA1321/exam/2018/Juin/Majeure/mft-MECA1321-exam-2018-Juin-Majeure.tex
Labels: Erreur

#562 Add 1 question of proba exam (January 2015)
  src/q5/stat-FSAB1105/exam/2015/2015.mk
  src/q5/stat-FSAB1105/exam/2015/Janvier/All/Makefile
  src/q5/stat-FSAB1105/exam/2015/Janvier/All/stat-FSAB1105-exam-2015-Janvier-All.tex
  src/q5/stat-FSAB1105/exam/2015/Janvier/Janvier.mk
Labels: Ajout

#576 Remove author and update formatting
  src/q5/mmc-MECA1901/exam/2017/Août/Mineure/mmc-MECA1901-exam-2017-Août-Mineure.tex
Labels: Amélioration

#554 Add missing file
  src/q5/complelec-ELEC1755/exam/2018/Janvier/All/examen_1755_janvier2018_Q1.pdf
Labels: Ajout

#579 Minor fixes to math 3 exam 2018 janvier
  src/q3/math-FSAB1103/exam/2018/Janvier/All/math-FSAB1103-exam-2018-Janvier-All.tex
Labels: Amélioration

#581 Add summary of fabmeca
  src/config.yml
  src/q5/fabmeca-MECA1451/fabmeca-MECA1451.mk
  src/q5/fabmeca-MECA1451/summary/Images/Couches.png
  src/q5/fabmeca-MECA1451/summary/Images/Explosion.png
  src/q5/fabmeca-MECA1451/summary/Images/Merchant.png
  src/q5/fabmeca-MECA1451/summary/Images/MerchantF.png
  src/q5/fabmeca-MECA1451/summary/Images/MerchantFO.png
  src/q5/fabmeca-MECA1451/summary/Images/Phase.png
  src/q5/fabmeca-MECA1451/summary/Images/carreblanc.png
  src/q5/fabmeca-MECA1451/summary/Images/electro.png
  src/q5/fabmeca-MECA1451/summary/Images/enrob.png
  src/q5/fabmeca-MECA1451/summary/Images/etau.png
  src/q5/fabmeca-MECA1451/summary/Images/fissures.png
  src/q5/fabmeca-MECA1451/summary/Images/flux.png
  src/q5/fabmeca-MECA1451/summary/Images/fusible.png
  src/q5/fabmeca-MECA1451/summary/Images/gaz.png
  src/q5/fabmeca-MECA1451/summary/Images/inclusion.png
  src/q5/fabmeca-MECA1451/summary/Images/laminage.png
  src/q5/fabmeca-MECA1451/summary/Images/mohr.png
  src/q5/fabmeca-MECA1451/summary/Images/mort.png
  src/q5/fabmeca-MECA1451/summary/Images/penetration.png
  src/q5/fabmeca-MECA1451/summary/Images/plasma.png
  src/q5/fabmeca-MECA1451/summary/Images/rabo.png
  src/q5/fabmeca-MECA1451/summary/Images/soudageRes.png
  src/q5/fabmeca-MECA1451/summary/Images/soudure_arc.png
  src/q5/fabmeca-MECA1451/summary/Images/submerge.png
  src/q5/fabmeca-MECA1451/summary/Images/tig.png
  src/q5/fabmeca-MECA1451/summary/Images/tournage.png
  src/q5/fabmeca-MECA1451/summary/Makefile
  src/q5/fabmeca-MECA1451/summary/fabmeca-MECA1451-summary.tex
Labels: Ajout

#567 Add exam of proba August 2016
  src/q5/stat-FSAB1105/exam/2016/Août/All/Makefile
  src/q5/stat-FSAB1105/exam/2016/Août/All/Q1_1.png
  src/q5/stat-FSAB1105/exam/2016/Août/All/stat-FSAB1105-exam-2016-Août-All.tex
  src/q5/stat-FSAB1105/exam/2016/Août/Août.mk
Labels: Ajout

#568 Add exam of prostoch (August 2018)
  src/q6/prostoch-INMA1731/exam/2018/Août/Août.mk
  src/q6/prostoch-INMA1731/exam/2018/Août/Majeure/Makefile
  src/q6/prostoch-INMA1731/exam/2018/Août/Majeure/prostoch-INMA1731-exam-2018-Août-Majeure.tex
Labels: Ajout

#569 Add some solutions in mmc exam (January 2018 MAJ)
  src/q5/mmc-MECA1901/exam/2018/Janvier/Majeure/mmc-MECA1901-exam-2018-Janvier-Majeure.tex
  src/q5/mmc-MECA1901/exam/mmc-MECA1901-exam.sty
Labels: Ajout

#582 Fix small math error in proba January 2017
  src/q5/stat-FSAB1105/exam/2017/Janvier/All/stat-FSAB1105-exam-2017-Janvier-All.tex
Labels: Amélioration

#587 Add.sh: fix issue #586
  add.sh
Labels: Amélioration, Résolu

#583 Summary compta: Improve text formatting and remove typos
  src/q8/compta-FSA1290/summary/compta-FSA1290-summary.tex
Labels: Amélioration

#591 Add cm1 and main file to opti q4 notes
  src/q4/opti-INMA1702/notes/Makefile
  src/q4/opti-INMA1702/notes/cm/cm1-problemes.tex
  src/q4/opti-INMA1702/notes/opti-INMA1702-notes.tex
Labels: Ajout

#593 Added a part of opti q4 notes
  src/q4/opti-INMA1702/notes/cm/cm1-problemes.tex
  src/q4/opti-INMA1702/notes/cm/cm2-formes.tex
  src/q4/opti-INMA1702/notes/opti-INMA1702-notes.tex
  src/q4/opti-INMA1702/summary/opti-INMA1702-summary.tex
Labels: Ajout

#584 Logique exam
  src/eplqa.sty
  src/q5/logique-INGI1101/exam/2017/Janvier/All/logique-INGI1101-exam-2017-Janvier-All.tex
  src/q5/logique-INGI1101/exam/2017/Janvier/Majeure/Makefile
  src/q5/logique-INGI1101/exam/2017/Janvier/Majeure/logique-INGI1101-exam-2017-Janvier-Majeure.tex
  src/q5/logique-INGI1101/exam/2017/Septembre/All/logique-INGI1101-exam-2017-Septembre-All.tex
  src/q5/logique-INGI1101/exam/2017/Septembre/Majeure/Makefile
  src/q5/logique-INGI1101/exam/2017/Septembre/Majeure/logique-INGI1101-exam-2017-Septembre-Majeure.tex
  src/q5/logique-INGI1101/exam/2018/Janvier/All/Makefile
  src/q5/logique-INGI1101/exam/2018/Janvier/All/logique-INGI1101-exam-2018-Janvier-All.tex
  src/q5/logique-INGI1101/exam/2018/Janvier/Majeure/Makefile
  src/q5/logique-INGI1101/exam/2018/Janvier/Majeure/logique-INGI1101-exam-2018-Janvier-Majeure.tex
Labels: Ajout

#599 Work on fem summary, small fixes to fem test
  src/q4/fem-MECA1120/summary/biblio.bib
  src/q4/fem-MECA1120/summary/fem-MECA1120-summary.tex
  src/q4/fem-MECA1120/test/2014/Avril/All/fem-MECA1120-test-2014-Avril-All.tex
Labels: Ajout, Amélioration

#596 Fixed issue and added cm3 to opti q4 notes
  src/q4/opti-INMA1702/notes/cm/cm1-problemes.tex
  src/q4/opti-INMA1702/notes/cm/cm2-formes.tex
  src/q4/opti-INMA1702/notes/cm/cm3-convexite.tex
  src/q4/opti-INMA1702/notes/img/convex.png
  src/q4/opti-INMA1702/notes/img/nonconvex.png
  src/q4/opti-INMA1702/notes/opti-INMA1702-notes.tex
Labels: Ajout, Erreur

#601 Add exam of proba (August 2018)
  src/q5/stat-FSAB1105/exam/2018/Septembre/All/Makefile
  src/q5/stat-FSAB1105/exam/2018/Septembre/All/stat-FSAB1105-exam-2018-Septembre-All.tex
  src/q5/stat-FSAB1105/exam/2018/Septembre/Septembre.mk
Labels: Ajout

#588 Fix issue #585
  src/eplbase.cls
Labels: Amélioration, Erreur, Résolu

#590 Insert directly the course name in hypertitle when using add.sh
  add.sh
  course_link.py
  templates/exam.tex
Labels: Amélioration
