Repository Gp2mv3/Syntheses, pull requests merged in 2018-09, with the labels that each got.

#615 [ELEC2532] Summary: Add name to node
  src/q8/analog-ELEC2532/summary/analog-ELEC2532-summary.tex
Labels: Erreur

#614 [FSAB1105] Formulaire 2: Fix small compilation error
  src/q5/stat-FSAB1105/formulaire2/stat-FSAB1105-formulaire.tex
Labels: Erreur

#613 [INGI1101] Exercices : fix compilation error
  src/q5/logique-INGI1101/exercises/TP/tp4.tex
Labels: Erreur

#611 [SINF1225] Summary: Fix wrong option in eplunits
  src/q4/coo-SINF1225/summary/coo-SINF1225-summary.tex
Labels: Erreur

#612 [MECA1120] 2014 test: \set command already defined
  src/q4/fem-MECA1120/test/2014/Avril/All/fem-MECA1120-test-2014-Avril-All.tex
Labels: Erreur

#606 [LINMA1702] Notes: add cm's 4 and 5
  src/q4/opti-INMA1702/notes/cm/cm1-problemes.tex
  src/q4/opti-INMA1702/notes/cm/cm2-formes.tex
  src/q4/opti-INMA1702/notes/cm/cm3-convexite.tex
  src/q4/opti-INMA1702/notes/cm/cm4-simplexe.tex
  src/q4/opti-INMA1702/notes/cm/cm5-dual.tex
  src/q4/opti-INMA1702/notes/opti-INMA1702-notes.tex
Labels: Ajout

#595 [SINF1252] Summary: Fixes to systinfo
  src/eplcommon.sty
  src/q4/os-SINF1252/summary/code/array.c
  src/q4/os-SINF1252/summary/code/async_sig.c
  src/q4/os-SINF1252/summary/code/calloc.c
  src/q4/os-SINF1252/summary/code/loop1.c
  src/q4/os-SINF1252/summary/code/loop2.c
  src/q4/os-SINF1252/summary/code/malloc.c
  src/q4/os-SINF1252/summary/code/mov.asm
  src/q4/os-SINF1252/summary/code/movl.asm
  src/q4/os-SINF1252/summary/code/non_init_data.c
  src/q4/os-SINF1252/summary/code/pass_by_value.c
  src/q4/os-SINF1252/summary/code/peterson.c
  src/q4/os-SINF1252/summary/code/philosopher.c
  src/q4/os-SINF1252/summary/code/pointer1.c
  src/q4/os-SINF1252/summary/code/pointer2.c
  src/q4/os-SINF1252/summary/code/pointer_arith.c
  src/q4/os-SINF1252/summary/code/pointer_arrow.c
  src/q4/os-SINF1252/summary/code/pointer_free.c
  src/q4/os-SINF1252/summary/code/prodcons.c
  src/q4/os-SINF1252/summary/code/rdv.c
  src/q4/os-SINF1252/summary/code/reader_writer.c
  src/q4/os-SINF1252/summary/code/struct_point.c
  src/q4/os-SINF1252/summary/code/struct_student.c
  src/q4/os-SINF1252/summary/code/tempo.c
  src/q4/os-SINF1252/summary/code/typecast.c
  src/q4/os-SINF1252/summary/code/typedef.c
  src/q4/os-SINF1252/summary/code/xchg.asm
  src/q4/os-SINF1252/summary/img/amdahl.png
  src/q4/os-SINF1252/summary/img/appelsbloquant.png
  src/q4/os-SINF1252/summary/img/appelssystemes.png
  src/q4/os-SINF1252/summary/img/bigendian.png
  src/q4/os-SINF1252/summary/img/littleendian.png
  src/q4/os-SINF1252/summary/img/mem.png
  src/q4/os-SINF1252/summary/img/mem2.png
  src/q4/os-SINF1252/summary/img/memcache1.png
  src/q4/os-SINF1252/summary/img/memhierarchie.png
  src/q4/os-SINF1252/summary/img/mempart.png
  src/q4/os-SINF1252/summary/img/memthread.png
  src/q4/os-SINF1252/summary/img/memtradadresses.png
  src/q4/os-SINF1252/summary/img/memvirt.png
  src/q4/os-SINF1252/summary/img/mmap.png
  src/q4/os-SINF1252/summary/img/mmu.png
  src/q4/os-SINF1252/summary/img/philosophes.png
  src/q4/os-SINF1252/summary/img/prodcons.png
  src/q4/os-SINF1252/summary/img/vonNeumann.png
  src/q4/os-SINF1252/summary/os-SINF1252-summary.tex
Labels: Amélioration, Fautes d'orthographe

#617 [SINF2335] Exam: remove <U+200B> characters
  src/q8/paradigms-SINF2335/exam/2016/Juin/All/paradigms-SINF2335-exam-2016-Juin-All.tex
Labels: Erreur

#616 [INMA2470] Summary: Fix \Edge error due to clash with babel package
  src/q8/modstoch-INMA2470/summary/modstoch-INMA2470-summary.tex
Labels: Erreur

#609 [MECA1901] Fix small errors in maj exam (January 2018)
  src/q5/mmc-MECA1901/exam/2018/Janvier/Majeure/mmc-MECA1901-exam-2018-Janvier-Majeure.tex
Labels: Amélioration

#610 [FSAB1302] Fix compilation errors
  src/q3/chimie-FSAB1302/exam/2014/Janvier/All/chimie-FSAB1302-exam-2014-Janvier-All.tex
  src/q3/chimie-FSAB1302/summary/chimie-FSAB1302-summary.tex
Labels: Erreur

#618 [INMA1510] Exam: Add some solutions
  src/q6/autolin-INMA1510/exam/2018/Juin/Majeure/autolin-INMA1510-exam-2018-Juin-Majeure.tex
Labels: Ajout
